name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Permissões explícitas necessárias para criar a branch 'output'
      contents: write 
      pages: write 
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          # É crucial que o checkout seja profundo para o GitHub Actions funcionar corretamente
          fetch-depth: 0 
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Alberth # Seu nome de usuário
          outputs: |
            dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Branch onde a imagem será salva
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
